# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
jdk = "21"
kotlin = "2.3.0"

fluxzero = "1.69.0"
spring-boot = "3.5.9"

detekt = "1.23.8"
logback = "1.5.26"

kotlin-logging = "7.0.14"

[libraries]

# Spring
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }

# Flux
fluxzero-sdk = { module = "io.fluxzero:sdk", version.ref = "fluxzero" }
fluxzero-test-server = { module = "io.fluxzero:test-server", version.ref = "fluxzero" }
fluxzero-proxy = { module = "io.fluxzero:proxy", version.ref = "fluxzero" }

# Monitoring
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm" , version.ref = "kotlin-logging"}

[plugins]
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }